
CC = gcc -m64 -Wno-unused-function
#CC = gcc-4.8

CFLAGS = -Wall -DFR_LINUX -DMTSTESTKIT -I./ 
	
#CFLAGS = -Wall			 	\
#	-DG_DISABLE_DEPRECATED 	 	\
#	-DGDK_DISABLE_DEPRECATED 	\
#	-DGDK_PIXBUF_DISABLE_DEPRECATED \
#	-DGTK_DISABLE_DEPRECATED -DFR_LINUX -DMTSTESTKIT -I./

# library path and names    
LIBS=-L/usr/lib/x86_64-linux-gnu -ldl -lm

GTKPAR=`pkg-config --cflags --libs gtk+-2.0 gmodule-2.0`
SRCMTS=../commons/
SRC = MtsTestKit.o ListClassDevices.o forlinux.o mts_tk_man.o sequence.o cmdpslave.o

MtsTestKit: $(SRC)
	$(CC) -Wall $(SRC) -o MtsTestKit $(GTKPAR) $(LIBS)

MtsTestKit.o: MtsTestKit.c MtsTestKit.h MtsGTK.h video_def.h
	$(CC) -c MtsTestKit.c -o MtsTestKit.o $(CFLAGS) $(GTKPAR) 

ListClassDevices.o: ListClassDevices.c MtsTestKit.h MtsGTK.h
	$(CC) -c ListClassDevices.c -o ListClassDevices.o $(CFLAGS) $(GTKPAR)

forlinux.o: $(SRCMTS)forlinux.c MtsTestKit.h
	$(CC) -c $(SRCMTS)forlinux.c -o forlinux.o $(CFLAGS) $(GTKPAR)

mts_tk_man.o: $(SRCMTS)mts_tk_man.c MtsTestKit.h
	$(CC) -c $(SRCMTS)mts_tk_man.c -o mts_tk_man.o $(CFLAGS) $(GTKPAR)

sequence.o: sequence.c cmdpslave.h MtsTestKit.h 
	$(CC) -c sequence.c -o sequence.o $(CFLAGS) $(GTKPAR)

cmdpslave.o: cmdpslave.c cmdpslave.h
	$(CC) -c cmdpslave.c -o cmdpslave.o $(CFLAGS) $(GTKPAR)

video_def.h: mtstestkit.glade
	./glade2include mtstestkit.glade video_def

clean: 
	rm -f *.o MtsTestKit

