static const char video_def[] =
"<?xml version=\"1.0\"?>"
"<interface>"
"  <requires lib=\"gtk+\" version=\"2.16\"/>"
"  <!-- interface-naming-policy project-wide -->"
"  <object class=\"GtkWindow\" id=\"window1\">"
"    <property name=\"border_width\">5</property>"
"    <property name=\"window_position\">center-on-parent</property>"
"    <child>"
"      <object class=\"GtkHBox\" id=\"hbox1\">"
"        <property name=\"visible\">True</property>"
"        <property name=\"border_width\">5</property>"
"        <child>"
"          <object class=\"GtkVBox\" id=\"vbox2\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"border_width\">5</property>"
"            <property name=\"spacing\">5</property>"
"            <child>"
"              <object class=\"GtkVBox\" id=\"vbox3\">"
"                <property name=\"visible\">True</property>"
"                <child>"
"                  <object class=\"GtkAspectFrame\" id=\"aspectframe3\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"double_buffered\">False</property>"
"                    <property name=\"label_xalign\">0.5</property>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"eventbox1\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"LabelHeader\">"
"                            <property name=\"width_request\">690</property>"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"double_buffered\">False</property>"
"                            <property name=\"ypad\">4</property>"
"                            <property name=\"label\" translatable=\"yes\">label</property>"
"                            <property name=\"justify\">center</property>"
"                            <property name=\"ellipsize\">end</property>"
"                            <property name=\"single_line_mode\">True</property>"
"                            <property name=\"track_visited_links\">False</property>"
"                            <attributes>"
"                              <attribute name=\"weight\" value=\"semibold\"/>"
"                            </attributes>"
"                          </object>"
"                        </child>"
"                      </object>"
"                    </child>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">False</property>"
"                    <property name=\"fill\">False</property>"
"                    <property name=\"padding\">5</property>"
"                    <property name=\"position\">0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkAspectFrame\" id=\"aspectframe2\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"double_buffered\">False</property>"
"                    <property name=\"label_xalign\">0.5</property>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"BkLabelRun\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"LabelRun\">"
"                            <property name=\"width_request\">690</property>"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"app_paintable\">True</property>"
"                            <property name=\"double_buffered\">False</property>"
"                            <property name=\"ypad\">4</property>"
"                            <property name=\"justify\">center</property>"
"                            <property name=\"single_line_mode\">True</property>"
"                            <property name=\"track_visited_links\">False</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                    </child>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">False</property>"
"                    <property name=\"fill\">False</property>"
"                    <property name=\"padding\">5</property>"
"                    <property name=\"position\">1</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkProgressBar\" id=\"ProgressBar\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"double_buffered\">False</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">False</property>"
"                    <property name=\"fill\">False</property>"
"                    <property name=\"padding\">7</property>"
"                    <property name=\"position\">2</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkHBox\" id=\"hbox3\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"spacing\">3</property>"
"                    <property name=\"homogeneous\">True</property>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"LabelAmpere\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"label\" translatable=\"yes\">mA</property>"
"                        <property name=\"justify\">center</property>"
"                        <property name=\"width_chars\">6</property>"
"                        <property name=\"single_line_mode\">True</property>"
"                        <property name=\"track_visited_links\">False</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">0</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"LabelVolt\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"label\" translatable=\"yes\">V</property>"
"                        <property name=\"justify\">center</property>"
"                        <property name=\"width_chars\">6</property>"
"                        <property name=\"single_line_mode\">True</property>"
"                        <property name=\"track_visited_links\">False</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">1</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"FreeLabel0\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"justify\">center</property>"
"                        <property name=\"width_chars\">6</property>"
"                        <property name=\"single_line_mode\">True</property>"
"                        <property name=\"track_visited_links\">False</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">2</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"FreeLabel1\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"justify\">center</property>"
"                        <property name=\"width_chars\">6</property>"
"                        <property name=\"single_line_mode\">True</property>"
"                        <property name=\"track_visited_links\">False</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">3</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"FreeLabel2\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"justify\">center</property>"
"                        <property name=\"width_chars\">6</property>"
"                        <property name=\"single_line_mode\">True</property>"
"                        <property name=\"track_visited_links\">False</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">4</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"FreeLabel3\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"justify\">center</property>"
"                        <property name=\"width_chars\">6</property>"
"                        <property name=\"single_line_mode\">True</property>"
"                        <property name=\"track_visited_links\">False</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">5</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"FreeLabel4\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"justify\">center</property>"
"                        <property name=\"width_chars\">6</property>"
"                        <property name=\"single_line_mode\">True</property>"
"                        <property name=\"track_visited_links\">False</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">6</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"FreeLabel5\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"justify\">center</property>"
"                        <property name=\"width_chars\">6</property>"
"                        <property name=\"single_line_mode\">True</property>"
"                        <property name=\"track_visited_links\">False</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">7</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"FreeLabel6\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"justify\">center</property>"
"                        <property name=\"width_chars\">6</property>"
"                        <property name=\"single_line_mode\">True</property>"
"                        <property name=\"track_visited_links\">False</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">8</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"FreeLabel7\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"justify\">center</property>"
"                        <property name=\"width_chars\">6</property>"
"                        <property name=\"single_line_mode\">True</property>"
"                        <property name=\"track_visited_links\">False</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">9</property>"
"                      </packing>"
"                    </child>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">False</property>"
"                    <property name=\"fill\">False</property>"
"                    <property name=\"position\">3</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkHBox\" id=\"hbox4\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"double_buffered\">False</property>"
"                    <property name=\"homogeneous\">True</property>"
"                    <child>"
"                      <object class=\"GtkAspectFrame\" id=\"aspectframe4\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"double_buffered\">False</property>"
"                        <property name=\"label_xalign\">0.5</property>"
"                        <child>"
"                          <object class=\"GtkEventBox\" id=\"bk_TxtAmpere\">"
"                            <property name=\"visible\">True</property>"
"                            <child>"
"                              <object class=\"GtkLabel\" id=\"TxtAmpere\">"
"                                <property name=\"visible\">True</property>"
"                                <property name=\"double_buffered\">False</property>"
"                                <property name=\"ypad\">3</property>"
"                                <property name=\"width_chars\">6</property>"
"                              </object>"
"                            </child>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"padding\">2</property>"
"                        <property name=\"position\">0</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkAspectFrame\" id=\"aspectframe5\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"label_xalign\">0.5</property>"
"                        <child>"
"                          <object class=\"GtkEventBox\" id=\"bk_TxtVolt\">"
"                            <property name=\"visible\">True</property>"
"                            <child>"
"                              <object class=\"GtkLabel\" id=\"TxtVolt\">"
"                                <property name=\"visible\">True</property>"
"                                <property name=\"ypad\">3</property>"
"                                <property name=\"width_chars\">6</property>"
"                              </object>"
"                            </child>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"padding\">2</property>"
"                        <property name=\"position\">1</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkAspectFrame\" id=\"aspectframe6\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"border_width\">3</property>"
"                        <property name=\"label_xalign\">0.5</property>"
"                        <child>"
"                          <object class=\"GtkEventBox\" id=\"bk_FreeText0\">"
"                            <property name=\"visible\">True</property>"
"                            <child>"
"                              <object class=\"GtkLabel\" id=\"FreeText0\">"
"                                <property name=\"visible\">True</property>"
"                                <property name=\"ypad\">3</property>"
"                                <property name=\"width_chars\">6</property>"
"                              </object>"
"                            </child>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"padding\">2</property>"
"                        <property name=\"position\">2</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkAspectFrame\" id=\"aspectframe7\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"border_width\">3</property>"
"                        <property name=\"label_xalign\">0.5</property>"
"                        <child>"
"                          <object class=\"GtkEventBox\" id=\"bk_FreeText1\">"
"                            <property name=\"visible\">True</property>"
"                            <child>"
"                              <object class=\"GtkLabel\" id=\"FreeText1\">"
"                                <property name=\"visible\">True</property>"
"                                <property name=\"ypad\">3</property>"
"                                <property name=\"width_chars\">6</property>"
"                              </object>"
"                            </child>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"padding\">2</property>"
"                        <property name=\"position\">3</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkAspectFrame\" id=\"aspectframe8\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"border_width\">3</property>"
"                        <property name=\"label_xalign\">0.5</property>"
"                        <child>"
"                          <object class=\"GtkEventBox\" id=\"bk_FreeText2\">"
"                            <property name=\"visible\">True</property>"
"                            <child>"
"                              <object class=\"GtkLabel\" id=\"FreeText2\">"
"                                <property name=\"visible\">True</property>"
"                                <property name=\"ypad\">3</property>"
"                                <property name=\"width_chars\">6</property>"
"                              </object>"
"                            </child>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"padding\">2</property>"
"                        <property name=\"position\">4</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkAspectFrame\" id=\"aspectframe9\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"border_width\">3</property>"
"                        <property name=\"label_xalign\">0.5</property>"
"                        <child>"
"                          <object class=\"GtkEventBox\" id=\"bk_FreeText3\">"
"                            <property name=\"visible\">True</property>"
"                            <child>"
"                              <object class=\"GtkLabel\" id=\"FreeText3\">"
"                                <property name=\"visible\">True</property>"
"                                <property name=\"ypad\">3</property>"
"                                <property name=\"width_chars\">6</property>"
"                              </object>"
"                            </child>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"padding\">2</property>"
"                        <property name=\"position\">5</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkAspectFrame\" id=\"aspectframe10\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"border_width\">3</property>"
"                        <property name=\"label_xalign\">0.5</property>"
"                        <child>"
"                          <object class=\"GtkEventBox\" id=\"bk_FreeText4\">"
"                            <property name=\"visible\">True</property>"
"                            <child>"
"                              <object class=\"GtkLabel\" id=\"FreeText4\">"
"                                <property name=\"visible\">True</property>"
"                                <property name=\"ypad\">3</property>"
"                                <property name=\"width_chars\">6</property>"
"                              </object>"
"                            </child>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"padding\">2</property>"
"                        <property name=\"position\">6</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkAspectFrame\" id=\"aspectframe11\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"border_width\">3</property>"
"                        <property name=\"label_xalign\">0.5</property>"
"                        <child>"
"                          <object class=\"GtkEventBox\" id=\"bk_FreeText5\">"
"                            <property name=\"visible\">True</property>"
"                            <child>"
"                              <object class=\"GtkLabel\" id=\"FreeText5\">"
"                                <property name=\"visible\">True</property>"
"                                <property name=\"ypad\">3</property>"
"                                <property name=\"width_chars\">6</property>"
"                              </object>"
"                            </child>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"padding\">2</property>"
"                        <property name=\"position\">7</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkAspectFrame\" id=\"aspectframe12\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"border_width\">3</property>"
"                        <property name=\"label_xalign\">0.5</property>"
"                        <child>"
"                          <object class=\"GtkEventBox\" id=\"bk_FreeText6\">"
"                            <property name=\"visible\">True</property>"
"                            <child>"
"                              <object class=\"GtkLabel\" id=\"FreeText6\">"
"                                <property name=\"visible\">True</property>"
"                                <property name=\"ypad\">3</property>"
"                                <property name=\"width_chars\">6</property>"
"                              </object>"
"                            </child>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"padding\">2</property>"
"                        <property name=\"position\">8</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkAspectFrame\" id=\"aspectframe13\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"border_width\">3</property>"
"                        <property name=\"label_xalign\">0.5</property>"
"                        <child>"
"                          <object class=\"GtkEventBox\" id=\"bk_FreeText7\">"
"                            <property name=\"visible\">True</property>"
"                            <child>"
"                              <object class=\"GtkLabel\" id=\"FreeText7\">"
"                                <property name=\"visible\">True</property>"
"                                <property name=\"ypad\">3</property>"
"                                <property name=\"width_chars\">6</property>"
"                              </object>"
"                            </child>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"padding\">2</property>"
"                        <property name=\"position\">9</property>"
"                      </packing>"
"                    </child>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">False</property>"
"                    <property name=\"fill\">False</property>"
"                    <property name=\"position\">4</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkScrolledWindow\" id=\"scrolledwindow1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <child>"
"                  <object class=\"GtkTextView\" id=\"textMTS\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"editable\">False</property>"
"                  </object>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkScrolledWindow\" id=\"scrolledwindow2\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <child>"
"                  <object class=\"GtkTextView\" id=\"textAnswer\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"editable\">False</property>"
"                  </object>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"position\">2</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkHButtonBox\" id=\"hbuttonbox1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"layout_style\">spread</property>"
"                <child>"
"                  <object class=\"GtkButton\" id=\"bt_script\">"
"                    <property name=\"label\" translatable=\"yes\">Avvia Script</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"receives_default\">True</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">False</property>"
"                    <property name=\"fill\">False</property>"
"                    <property name=\"position\">0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkButton\" id=\"bt_selection\">"
"                    <property name=\"label\" translatable=\"yes\">Cambia Selezione</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"receives_default\">True</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">False</property>"
"                    <property name=\"fill\">False</property>"
"                    <property name=\"position\">1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"position\">3</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkFrame\" id=\"frame1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"label_xalign\">0</property>"
"                <child>"
"                  <object class=\"GtkAlignment\" id=\"alignment1\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"border_width\">10</property>"
"                    <child>"
"                      <object class=\"GtkHBox\" id=\"hbox2\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"spacing\">10</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"label2\">"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"xalign\">1</property>"
"                            <property name=\"label\" translatable=\"yes\">TK port:</property>"
"                            <property name=\"justify\">right</property>"
"                            <property name=\"track_visited_links\">False</property>"
"                          </object>"
"                          <packing>"
"                            <property name=\"expand\">False</property>"
"                            <property name=\"fill\">False</property>"
"                            <property name=\"position\">0</property>"
"                          </packing>"
"                        </child>"
"                        <child>"
"                          <object class=\"GtkAspectFrame\" id=\"aspectframe14\">"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"label_xalign\">0</property>"
"                            <child>"
"                              <object class=\"GtkEventBox\" id=\"bk_LabelExtName\">"
"                                <property name=\"visible\">True</property>"
"                                <child>"
"                                  <object class=\"GtkLabel\" id=\"LabelExtName\">"
"                                    <property name=\"visible\">True</property>"
"                                    <property name=\"xalign\">0</property>"
"                                    <property name=\"ypad\">3</property>"
"                                    <property name=\"width_chars\">25</property>"
"                                  </object>"
"                                </child>"
"                              </object>"
"                            </child>"
"                          </object>"
"                          <packing>"
"                            <property name=\"position\">1</property>"
"                          </packing>"
"                        </child>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"label3\">"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"xalign\">1</property>"
"                            <property name=\"label\" translatable=\"yes\">MTS Port:</property>"
"                            <property name=\"justify\">right</property>"
"                          </object>"
"                          <packing>"
"                            <property name=\"expand\">False</property>"
"                            <property name=\"fill\">False</property>"
"                            <property name=\"position\">2</property>"
"                          </packing>"
"                        </child>"
"                        <child>"
"                          <object class=\"GtkAspectFrame\" id=\"aspectframe15\">"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"label_xalign\">0</property>"
"                            <child>"
"                              <object class=\"GtkEventBox\" id=\"bk_LabelProtName\">"
"                                <property name=\"visible\">True</property>"
"                                <child>"
"                                  <object class=\"GtkLabel\" id=\"LabelProtName\">"
"                                    <property name=\"visible\">True</property>"
"                                    <property name=\"xalign\">0</property>"
"                                    <property name=\"ypad\">3</property>"
"                                    <property name=\"width_chars\">40</property>"
"                                    <property name=\"track_visited_links\">False</property>"
"                                  </object>"
"                                </child>"
"                              </object>"
"                            </child>"
"                          </object>"
"                          <packing>"
"                            <property name=\"position\">3</property>"
"                          </packing>"
"                        </child>"
"                      </object>"
"                    </child>"
"                  </object>"
"                </child>"
"                <child type=\"label\">"
"                  <object class=\"GtkLabel\" id=\"label1\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"label\" translatable=\"yes\">Com info</property>"
"                    <property name=\"use_markup\">True</property>"
"                  </object>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">4</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkVBox\" id=\"vbox1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"border_width\">5</property>"
"            <property name=\"spacing\">2</property>"
"            <child>"
"              <object class=\"GtkAspectFrame\" id=\"aspectframe1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"label_xalign\">0</property>"
"                <property name=\"shadow_type\">out</property>"
"                <child>"
"                  <object class=\"GtkDrawingArea\" id=\"drawingarea1\">"
"                    <property name=\"width_request\">230</property>"
"                    <property name=\"height_request\">130</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"double_buffered\">False</property>"
"                  </object>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkHBox\" id=\"hbox5\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"border_width\">4</property>"
"                <child>"
"                  <object class=\"GtkVBox\" id=\"vbox4\">"
"                    <property name=\"width_request\">20</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"double_buffered\">False</property>"
"                    <property name=\"resize_mode\">immediate</property>"
"                    <property name=\"spacing\">5</property>"
"                    <property name=\"homogeneous\">True</property>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor0\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor0\">"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"xalign\">1</property>"
"                            <property name=\"label\" translatable=\"yes\">      </property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"fill\">False</property>"
"                        <property name=\"position\">0</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor1\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor1\">"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"double_buffered\">False</property>"
"                            <attributes>"
"                              <attribute name=\"background\" value=\"#ffff00000000\"/>"
"                            </attributes>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">1</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor2\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor2\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">2</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor3\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor3\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">3</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor4\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor4\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">4</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor5\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor5\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">5</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor6\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor6\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">6</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor7\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor7\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">7</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor8\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor8\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">8</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor9\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor9\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">9</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor10\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor10\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">10</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor11\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor11\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">11</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor12\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor12\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">12</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor13\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor13\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">13</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor14\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor14\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">14</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor15\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor15\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">15</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor16\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor16\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">16</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor17\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor17\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">17</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor18\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor18\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">18</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor19\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor19\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">19</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor20\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor20\">"
"                            <property name=\"visible\">True</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">20</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkEventBox\" id=\"stepcolor21\">"
"                        <property name=\"visible\">True</property>"
"                        <child>"
"                          <object class=\"GtkLabel\" id=\"lstepcolor21\">"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"width_chars\">2</property>"
"                          </object>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">21</property>"
"                      </packing>"
"                    </child>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">False</property>"
"                    <property name=\"position\">0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkVBox\" id=\"vbox5\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"double_buffered\">False</property>"
"                    <property name=\"spacing\">5</property>"
"                    <property name=\"homogeneous\">True</property>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext0\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"double_buffered\">False</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                        <property name=\"label\" translatable=\"yes\">abc</property>"
"                        <property name=\"width_chars\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">0</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext1\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">1</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext2\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">2</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext3\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">3</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext4\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">4</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext5\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">5</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext6\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">6</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext7\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">7</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext8\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">8</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext9\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">9</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext10\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">10</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext11\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">11</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext12\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">12</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext13\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">13</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext14\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">14</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext15\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">15</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext16\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">16</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext17\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">17</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext18\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">18</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext19\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">19</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext20\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">20</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkLabel\" id=\"steptext21\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"xalign\">0</property>"
"                        <property name=\"xpad\">5</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">21</property>"
"                      </packing>"
"                    </child>"
"                  </object>"
"                  <packing>"
"                    <property name=\"position\">1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">1</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"  <object class=\"GtkListStore\" id=\"liststore1\">"
"    <columns>"
"      <!-- column-name mts -->"
"      <column type=\"gchararray\"/>"
"    </columns>"
"  </object>"
"  <object class=\"GtkWindow\" id=\"ListClassDevices\">"
"    <property name=\"width_request\">300</property>"
"    <property name=\"height_request\">500</property>"
"    <property name=\"modal\">True</property>"
"    <property name=\"window_position\">center</property>"
"    <child>"
"      <object class=\"GtkVBox\" id=\"vbox6\">"
"        <property name=\"visible\">True</property>"
"        <property name=\"double_buffered\">False</property>"
"        <property name=\"border_width\">6</property>"
"        <child>"
"          <object class=\"GtkHBox\" id=\"hbox6\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"border_width\">2</property>"
"            <child>"
"              <object class=\"GtkImage\" id=\"image1\">"
"                <property name=\"visible\">True</property>"
"              </object>"
"              <packing>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkVButtonBox\" id=\"vbuttonbox1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"homogeneous\">True</property>"
"                <property name=\"layout_style\">spread</property>"
"                <child>"
"                  <object class=\"GtkRadioButton\" id=\"radiobutton1\">"
"                    <property name=\"label\" translatable=\"yes\">Program</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"receives_default\">False</property>"
"                    <property name=\"draw_indicator\">True</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">False</property>"
"                    <property name=\"fill\">False</property>"
"                    <property name=\"position\">0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkRadioButton\" id=\"radiobutton2\">"
"                    <property name=\"label\" translatable=\"yes\">Collaudo</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"receives_default\">False</property>"
"                    <property name=\"draw_indicator\">True</property>"
"                    <property name=\"group\">radiobutton1</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">False</property>"
"                    <property name=\"fill\">False</property>"
"                    <property name=\"position\">1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"position\">0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkScrolledWindow\" id=\"scrolledwindow3\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"can_focus\">True</property>"
"            <property name=\"border_width\">2</property>"
"            <property name=\"hscrollbar_policy\">automatic</property>"
"            <property name=\"shadow_type\">etched-in</property>"
"            <child>"
"              <object class=\"GtkTreeView\" id=\"treeview\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"model\">liststore1</property>"
"                <property name=\"headers_clickable\">False</property>"
"                <property name=\"enable_search\">False</property>"
"                <property name=\"show_expanders\">False</property>"
"                <child>"
"                  <object class=\"GtkTreeViewColumn\" id=\"mts\">"
"                    <property name=\"resizable\">True</property>"
"                    <property name=\"title\">mts</property>"
"                    <child>"
"                      <object class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/>"
"                      <attributes>"
"                        <attribute name=\"text\">0</attribute>"
"                      </attributes>"
"                    </child>"
"                  </object>"
"                </child>"
"              </object>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">1</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHButtonBox\" id=\"hbuttonbox2\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"border_width\">10</property>"
"            <child>"
"              <object class=\"GtkButton\" id=\"button1\">"
"                <property name=\"label\" translatable=\"yes\">OK</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"fill\">False</property>"
"            <property name=\"position\">2</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"  <object class=\"GtkWindow\" id=\"InputBox\">"
"    <property name=\"border_width\">10</property>"
"    <child>"
"      <object class=\"GtkVBox\" id=\"vbox8\">"
"        <property name=\"visible\">True</property>"
"        <property name=\"spacing\">5</property>"
"        <child>"
"          <object class=\"GtkHBox\" id=\"hbox9\">"
"            <property name=\"visible\">True</property>"
"            <child>"
"              <object class=\"GtkLabel\" id=\"ib_txt\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"xalign\">1</property>"
"                <property name=\"label\" translatable=\"yes\">label</property>"
"              </object>"
"              <packing>"
"                <property name=\"padding\">5</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkEntry\" id=\"ib_val\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"invisible_char\">&#x25CF;</property>"
"              </object>"
"              <packing>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkLabel\" id=\"ib_lbl\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"label\" translatable=\"yes\">label</property>"
"          </object>"
"          <packing>"
"            <property name=\"position\">1</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHButtonBox\" id=\"hbuttonbox3\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"spacing\">25</property>"
"            <property name=\"layout_style\">center</property>"
"            <child>"
"              <object class=\"GtkButton\" id=\"ib_ok\">"
"                <property name=\"label\" translatable=\"yes\">OK</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkButton\" id=\"ib_abort\">"
"                <property name=\"label\" translatable=\"yes\">Abort</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">2</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"</interface>";
